### ISSUE TITLE
largest_prime_factor(10) is broken

### ISSUE THREAD

**Issue by peterhurford** [peterhurford/polygot-euler#2]

**Comment by peterhurford** [comment]
`sqrt` approach doesn't work, but `/2` would.  However, this is slow.  Can we use `sqrt` in the case of large numbers?

**Comment by khalidharun** [comment]
Ask @abelcastilloavant.  He studied this stuff for a living.

**Comment by peterhurford** [comment]
@khalidharun suggested memoizing to me.

**Comment by khalidharun** [comment]
@peterhurford Here's a recursive approach to finding `all_factors`.  Should me muuuuuch faster.  I would suspect faster than the sqrt approach.

https://gist.github.com/khalidharun/9df44e2174737a662fa2

**Comment by abelcastilloavant** [comment]
If you put `sqrt(n)` instead of `n-1` in 

https://github.com/peterhurford/polygot-euler/blob/master/p003/p003.R#L7

you'll be fine. If you haven't found a prime factor by `sqrt(n)`, then you have a prime number.

Here, you do need to take `. / 2` instead of `sqrt(.)`:
https://github.com/peterhurford/polygot-euler/blob/master/p003/p003.R#L14

Example: `194 = 97 * 2`, but its square root is close to `14`.

**Comment by peterhurford** [comment]
@khalidharun @abelcastilloavant Both of those approaches aren't sufficiently performant on the large number needed (600851475143), so I went with a new approach: https://github.com/peterhurford/polygot-euler/blob/79e77e3d3202f88c83a69b4d7793d936b7a84aad/p003/p003.R#L4-L14
